name: panna_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "^3.8.1"
  flutter: ">=3.0.0"

include: package:flutter_lints/flutter.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^5.0.0
  talker: ^1.0.0
  envied: ^2.0.0
  forui: ^0.1.0
  go_router: ^13.1.0
  go_router_builder: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  responsive_framework: ^0.1.7
  hugeicons: ^1.0.2
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  json_annotation: ^4.7.0
  json_serializable: ^6.6.0
  formz: ^0.6.1
  supabase: ^2.0.7
  supabase_flutter: ^2.3.2
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  firebase_messaging: ^14.7.19
  firebase_crashlytics: ^3.0.0
  flutter_local_notifications: ^18.0.1
  device_preview: ^1.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^2.5.0
  carousel_slider: ^5.0.0
  carousel_slider_plus: ^7.0.1
  charts_flutter_new: ^0.12.0
  flutter_charts: ^0.5.2
  fl_chart: ^0.70.2
  pie_chart: ^5.4.0
  google_fonts: ^6.2.1
  http: ^1.2.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  timeago: ^3.1.0
  date_count_down: ^3.0.0
  app_links: ^5.0.0
  scroll_date_picker: ^3.8.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  collection: ^1.18.0
  dropdown_button2: ^2.0.0
  dropdown_search: ^5.0.3
  flutter_markdown: ^0.7.6+2
  settings_ui: ^2.0.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.0
  flutter_gen_runner: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_gen:
  output: lib/product/generation/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

scripts:
  lang: flutter pub run easy_localization:generate \
        -O lib/product/init/lang \
        -f keys \
        -o locale_keys.g.dart \
        --source-dir assets/translations
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  pubGet: sh scripts/pub_get.sh

flutter:
  uses-material-design: true
