name: panna_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "^3.8.1"
  flutter: ">=3.0.0"

include: package:flutter_lints/flutter.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  talker: ^4.9.0
  envied: ^1.1.1
  forui: ^0.12.0
  go_router: ^15.2.3
  go_router_builder: ^3.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  get_it: ^8.0.3
  injectable: ^2.4.0
  responsive_framework: ^1.1.1
  hugeicons: ^0.0.11
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  formz: ^0.8.0
  supabase: ^2.0.8
  supabase_flutter: ^2.4.0
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  firebase_crashlytics: ^4.0.0
  flutter_local_notifications: ^19.2.1
  device_preview: ^1.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  carousel_slider: ^5.1.1
  carousel_slider_plus: ^7.0.1
  flutter_charts: ^0.5.2
  fl_chart: ^1.0.0
  pie_chart: ^5.4.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  url_launcher: ^6.2.5
  share_plus: ^11.0.0
  timeago: ^3.6.0
  date_count_down: ^3.0.0
  app_links: ^6.4.0
  scroll_date_picker: ^3.8.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  collection: ^1.18.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^6.0.2
  flutter_markdown: ^0.7.7
  settings_ui: ^2.0.2
  package_info_plus: ^8.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_gen:
  output: lib/product/generation/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

scripts:
  lang: flutter pub run easy_localization:generate \
        -O lib/product/init/lang \
        -f keys \
        -o locale_keys.g.dart \
        --source-dir assets/translations
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  pubGet: sh scripts/pub_get.sh

flutter:
  uses-material-design: true
